select ca.UNIVERSAL_CONTENT_ID as UUC_ID,
upper(cr.CONTENT_ID) as OV_CODE,
ca.CONTENT_TITLE as ASSET_DEFAULT_TITLE,
ca.CONTENT_PAGE_URL as CONTENT_URL,
ca.DLVRY_URL,
ca.DLVRY_URL_ID,
ca.CDS_CONTENT_TYPE_CD as CONTENT_TYPE_ID,
ca.UT_LVL_10_CD as UT10_CODE,
ca.UT_LVL_15_CD as UT15_CODE,
ca.UT_LVL_17_CD as UT17_CODE,
ca.UT_LVL_20_CD as UT20_CODE,
ca.UT_LVL_30_CD as UT30_CODE,
ca.CDS_LANG_CD as LANG_CODE,
SUBSTRING(ca.CTRY_LIST, 1, 2) as COUNTRY_CODE,
4 as PARTCOL
from v2digt2.V_CDS_CONTENT_CORE_ATTRBT ca
left join v2digt2.V_CDS_CONTENT_CORE_RELSHP cr on cr.UNIVERSAL_CONTENT_ID = ca.UNIVERSAL_CONTENT_ID
and cr.CONTENT_RELSHP_TYPE  = 'alias' and cr.CONTENT_TYPE_ID= 'OV'
and ca.Content_stat_cd = 'FINAL'