MERGE INTO MAP_CORE.MCT_CDS_ASSET mca
USING ( VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?))
AS SOURCE (UUC_ID,ASSET_DEFAULT_TITLE,CONTENT_URL,DLVRY_URL,DLVRY_URL_ID,UT10_CODE,UT15_CODE,UT17_CODE,UT20_CODE,UT30_CODE,COUNTRY_CODE,LANG_CODE,CONTENT_TYPE_ID,OV_CODE)
ON mca.UUC_ID = SOURCE.UUC_ID
WHEN MATCHED THEN UPDATE SET
mca.ASSET_DEFAULT_TITLE = SOURCE.ASSET_DEFAULT_TITLE,
mca.CONTENT_TYPE_ID = SOURCE.CONTENT_TYPE_ID,
mca.CONTENT_URL = SOURCE.CONTENT_URL,
mca.COUNTRY_CODE = SOURCE.COUNTRY_CODE,
mca.DLVRY_URL = SOURCE.DLVRY_URL,
mca.DLVRY_URL_ID = SOURCE.DLVRY_URL_ID,
mca.LANG_CODE = SOURCE.LANG_CODE,
mca.OV_CODE = SOURCE.OV_CODE,
mca.UT10_CODE = SOURCE.UT10_CODE,
mca.UT15_CODE = SOURCE.UT15_CODE,
mca.UT17_CODE = SOURCE.UT17_CODE,
mca.UT20_CODE = SOURCE.UT20_CODE,
mca.UT30_CODE = SOURCE.UT30_CODE
WHEN NOT MATCHED THEN INSERT (UUC_ID,ASSET_DEFAULT_TITLE,CONTENT_URL,DLVRY_URL,DLVRY_URL_ID,UT10_CODE,UT15_CODE,UT17_CODE,UT20_CODE,UT30_CODE,COUNTRY_CODE,LANG_CODE,CONTENT_TYPE_ID,OV_CODE)
VALUES (SOURCE.UUC_ID,SOURCE.ASSET_DEFAULT_TITLE,SOURCE.CONTENT_URL,SOURCE.DLVRY_URL,SOURCE.DLVRY_URL_ID,SOURCE.UT10_CODE,SOURCE.UT15_CODE,SOURCE.UT17_CODE,SOURCE.UT20_CODE,SOURCE.UT30_CODE,SOURCE.COUNTRY_CODE,SOURCE.LANG_CODE,SOURCE.CONTENT_TYPE_ID,SOURCE.OV_CODE)