MERGE INTO MAP_CORE.MCT_COP_XREF mcx
USING ( VALUES (?,?,?,?,?,?,?))
AS SOURCE (URN_IDM_COMP , DOM_BUY_GRP, SAP_CUST_NUM, prmry_st_Prov_name, MAIN_DOM_CLIENT_ID , MAIN_IND_CD, src_UPDT_TS)
ON mcx.IDM_COMPANY_ID = SOURCE.URN_IDM_COMP
WHEN MATCHED THEN UPDATE SET
mcx.DOM_BUY_GRP = SOURCE.DOM_BUY_GRP,
mcx.SAP_CUST_NUM = SOURCE.SAP_CUST_NUM,
mcx.prmry_st_Prov_name = SOURCE.prmry_st_Prov_name,
mcx.MAIN_DOM_CLIENT_ID = SOURCE.MAIN_DOM_CLIENT_ID,
mcx.MAIN_IND_CD = SOURCE.MAIN_IND_CD,
mcx.SRC_UPDATE_TS = SOURCE.src_UPDT_TS
WHEN NOT MATCHED THEN INSERT (IDM_COMPANY_ID , DOM_BUY_GRP, SAP_CUST_NUM, prmry_st_Prov_name, MAIN_DOM_CLIENT_ID , MAIN_IND_CD, SRC_UPDATE_TS)
VALUES (SOURCE.URN_IDM_COMP,SOURCE.DOM_BUY_GRP,SOURCE.SAP_CUST_NUM,SOURCE.prmry_st_Prov_name,SOURCE.MAIN_DOM_CLIENT_ID,SOURCE.MAIN_IND_CD,SOURCE.src_UPDT_TS)