apiVersion: v1
kind: Secret
metadata:
  name: k8s-etlframework  #name will be used in other yaml files (MUST MATCH)
type: Opaque
stringData:
  # required for using the ETL FRAMEWORK v1 on a cluster
  # additional IDs will be available in subsequent versions
  BASE_DB_ENDPOINT: full-db-path:port/typelikeBLUDB
  BASE_DB_USER_ID: dbUserIdOrFunctionalId
  BASE_DB_PASSWORD: dbUserPassword
  
  # can add additional secrets here
 
  